# Site settings

# REQUIRED CHANGES
# Edit next line, providing your own name.
title: Katrina H. Turner | Professional Portfolio
# Edit next line, replacing 'techfolios' with your github username
url: "https://KatrinaTurner.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: igorpro

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]
